import type { RegionOverlay } from './types.js';

export const EU: RegionOverlay = {
  region: 'EU',
  displayName: 'European Union — EU AI Act',
  primaryLaw: 'Regulation (EU) 2024/1689 (EU AI Act)',
  effectiveDate: '2026-08-02',
  complianceMultiplier: 0.95,
  mandatoryGates: [
    'transparency',
    'human-oversight',
    'accountability',
    'ai-governance',
    'security',
  ],
  weights: {
    'transparency': 0.12,
    'human-oversight': 0.12,
    'accountability': 0.11,
    'ai-governance': 0.12,
    'security': 0.10,
    'fairness': 0.10,
    'privacy': 0.09,
    'reliability': 0.08,
    'data-governance': 0.08,
    'model-governance': 0.07,
    'deployment': 0.06,
    'incident-response': 0.05,
  },
  controls: [
    { id: 'eu-001', name: 'High-Risk System Classification', domain: 'ai-governance', mandatory: true, reference: 'EU AI Act Art. 6' },
    { id: 'eu-002', name: 'Conformity Assessment', domain: 'ai-governance', mandatory: true, reference: 'EU AI Act Art. 43' },
    { id: 'eu-003', name: 'CE Marking', domain: 'ai-governance', mandatory: true, reference: 'EU AI Act Art. 49' },
    { id: 'eu-004', name: 'EU Database Registration', domain: 'ai-governance', mandatory: true, reference: 'EU AI Act Art. 51' },
    { id: 'eu-005', name: 'Technical Documentation', domain: 'documentation', mandatory: true, reference: 'EU AI Act Annex IV' },
    { id: 'eu-006', name: 'Transparency Disclosure to Users', domain: 'transparency', mandatory: true, reference: 'EU AI Act Art. 13' },
    { id: 'eu-007', name: 'Human Oversight Measures', domain: 'human-oversight', mandatory: true, reference: 'EU AI Act Art. 14' },
    { id: 'eu-008', name: 'Accuracy, Robustness, Cybersecurity', domain: 'security', mandatory: true, reference: 'EU AI Act Art. 15' },
    { id: 'eu-009', name: 'GPAI Model Transparency', domain: 'transparency', mandatory: true, reference: 'EU AI Act Art. 53' },
    { id: 'eu-010', name: 'Fundamental Rights Impact Assessment', domain: 'fairness', mandatory: true, reference: 'EU AI Act Art. 27' },
    { id: 'eu-011', name: 'Post-Market Monitoring', domain: 'incident-response', mandatory: true, reference: 'EU AI Act Art. 72' },
    { id: 'eu-012', name: 'Incident Reporting to Authorities', domain: 'incident-response', mandatory: true, reference: 'EU AI Act Art. 73' },
  ],
};
