import type { RegionOverlay } from './types.js';

export const GLOBAL: RegionOverlay = {
  region: 'GLOBAL',
  displayName: 'Global — ISO/IEC 42001:2023 AI Management System',
  primaryLaw: 'ISO/IEC 42001:2023 (AI Management System Standard)',
  effectiveDate: '2023-12-18',
  complianceMultiplier: 0.90,
  mandatoryGates: [
    'ai-governance',
    'accountability',
    'transparency',
    'risk-management',
  ],
  weights: {
    'ai-governance': 0.13,
    'accountability': 0.12,
    'transparency': 0.11,
    'risk-management': 0.11,
    'human-oversight': 0.10,
    'security': 0.09,
    'fairness': 0.09,
    'privacy': 0.08,
    'reliability': 0.08,
    'data-governance': 0.07,
    'incident-response': 0.06,
    'documentation': 0.06,
  },
  controls: [
    { id: 'iso-001', name: 'AI Policy Statement', domain: 'ai-governance', mandatory: true, reference: 'ISO 42001 §5.2' },
    { id: 'iso-002', name: 'Organizational Roles & Responsibilities', domain: 'accountability', mandatory: true, reference: 'ISO 42001 §5.3' },
    { id: 'iso-003', name: 'AI Risk Assessment Process', domain: 'risk-management', mandatory: true, reference: 'ISO 42001 §6.1' },
    { id: 'iso-004', name: 'AI Objectives & Planning', domain: 'ai-governance', mandatory: true, reference: 'ISO 42001 §6.2' },
    { id: 'iso-005', name: 'AI System Impact Assessment', domain: 'accountability', mandatory: true, reference: 'ISO 42001 Annex A §A.5' },
    { id: 'iso-006', name: 'Data Management for AI', domain: 'data-governance', mandatory: true, reference: 'ISO 42001 Annex A §A.8' },
    { id: 'iso-007', name: 'AI System Life Cycle Management', domain: 'model-governance', mandatory: true, reference: 'ISO 42001 Annex A §A.9' },
    { id: 'iso-008', name: 'Human Oversight Mechanisms', domain: 'human-oversight', mandatory: true, reference: 'ISO 42001 Annex A §A.6' },
    { id: 'iso-009', name: 'Transparency & Explainability Policy', domain: 'transparency', mandatory: true, reference: 'ISO 42001 Annex A §A.7' },
    { id: 'iso-010', name: 'Documented Information & Records', domain: 'documentation', mandatory: true, reference: 'ISO 42001 §7.5' },
    { id: 'iso-011', name: 'Internal Audit Programme', domain: 'accountability', mandatory: true, reference: 'ISO 42001 §9.2' },
    { id: 'iso-012', name: 'Management Review', domain: 'ai-governance', mandatory: true, reference: 'ISO 42001 §9.3' },
    { id: 'iso-013', name: 'Continual Improvement Process', domain: 'incident-response', mandatory: true, reference: 'ISO 42001 §10.2' },
  ],
};
