// Zenith AI OS — Default Audit Framework Seed
// 12 domains × ~5 controls each = 60 default controls

import type { AuditDomain } from '../../aios-core/src/types/audit.types';

export const ZENITH_AIOS_FRAMEWORK_V1: { name: string; version: string; domains: AuditDomain[] } = {
  name: 'Zenith AI OS Standard',
  version: '1.0.0',
  domains: [
    {
      id: 'd-01', name: 'Identity & Context Layer', slug: 'identity-context',
      description: 'User identity resolution, tenant isolation, session and context propagation',
      weight: 0.10,
      controls: [
        { id: 'c-01-01', domain_id: 'd-01', name: 'Tenant Identity Resolution', description: 'Every request resolves to a tenant organization', expected_standard: 'All API requests resolve organization_id before processing', evidence_required: 'Middleware code, RLS policies, test coverage', scoring_guidance: { '0': 'No tenant resolution', '1': 'Manual per-route', '2': 'Middleware exists but incomplete', '3': 'Consistent middleware', '4': 'Middleware + audit log + freshness check', '5': 'Full context service with conflict detection' }, risk_if_missing: 'Data leakage across tenants — CRITICAL', remediation_guidance: 'Implement context middleware that resolves org from JWT on every request', weight: 2.0, severity: 'critical', is_required: true },
        { id: 'c-01-02', domain_id: 'd-01', name: 'User Role Resolution', description: 'User role and permissions resolved before any action', expected_standard: 'Permission checks on all protected routes and actions', evidence_required: 'RBAC implementation, permission service, test cases', scoring_guidance: { '0': 'No RBAC', '1': 'Basic role check', '2': 'Role check without permissions', '3': 'Role + permission system', '4': 'Full RBAC with audit', '5': 'Hierarchical permissions, explainable, audited' }, risk_if_missing: 'Privilege escalation, unauthorized access', remediation_guidance: 'Implement permission service with role-based and resource-based checks', weight: 1.5, severity: 'critical', is_required: true },
        { id: 'c-01-03', domain_id: 'd-01', name: 'Context Propagation', description: 'Context passed to all agents and tools', expected_standard: 'All agent/tool invocations receive enriched context', evidence_required: 'Context service code, propagation tests', scoring_guidance: { '0': 'No context', '1': 'Manual context passing', '2': 'Partial context propagation', '3': 'Consistent context service', '4': 'Context + snapshots + freshness', '5': 'Full context engine with conflict resolution' }, risk_if_missing: 'Agents acting without proper context — wrong decisions', remediation_guidance: 'Build context service that auto-enriches all agent/tool calls', weight: 1.5, severity: 'high', is_required: true },
        { id: 'c-01-04', domain_id: 'd-01', name: 'Context Snapshots', description: 'Context captured before critical actions', expected_standard: 'Snapshot created before any high-risk tool or agent action', evidence_required: 'Snapshot tables, snapshot creation logic', scoring_guidance: { '0': 'No snapshots', '1': 'Manual snapshots only', '2': 'Some automatic snapshots', '3': 'Automatic on high-risk actions', '4': 'All critical actions + rollback support', '5': 'Full snapshot lifecycle with replay' }, risk_if_missing: 'Cannot debug or rollback after context-dependent failures', remediation_guidance: 'Auto-snapshot context before risk_level >= high actions', weight: 1.0, severity: 'high', is_required: false },
        { id: 'c-01-05', domain_id: 'd-01', name: 'Context Freshness', description: 'Stale context detected and handled', expected_standard: 'Context freshness checked before agent decisions', evidence_required: 'Freshness scoring, stale context alerts', scoring_guidance: { '0': 'No freshness', '1': 'Manual expiry only', '2': 'TTL-based expiry', '3': 'Freshness scoring + alerts', '4': 'Auto-refresh stale context', '5': 'Predictive freshness with conflict resolution' }, risk_if_missing: 'Agents making decisions on outdated information', remediation_guidance: 'Implement context freshness scoring and auto-invalidation', weight: 1.0, severity: 'medium', is_required: false },
      ],
    },
    {
      id: 'd-02', name: 'Memory & State Management', slug: 'memory-state',
      description: 'Durable memory fabric, embeddings, permissions, and retrieval',
      weight: 0.08,
      controls: [
        { id: 'c-02-01', domain_id: 'd-02', name: 'Durable Memory Exists', description: 'Long-term memory persisted across sessions', expected_standard: 'Memory fabric with typed memory categories', evidence_required: 'Memory tables, memory service code', scoring_guidance: { '0': 'No persistent memory', '1': 'Session-only memory', '2': 'Basic database persistence', '3': 'Typed memory with CRUD', '4': 'Full memory fabric with permissions', '5': 'Memory fabric with embeddings + audit + pruning' }, risk_if_missing: 'Agents have no learning or continuity across sessions', remediation_guidance: 'Implement memory_items table with typed memory categories', weight: 2.0, severity: 'high', is_required: true },
        { id: 'c-02-02', domain_id: 'd-02', name: 'Memory Permissions', description: 'Memory access controlled by permissions', expected_standard: 'Memory reads/writes require permission checks', evidence_required: 'Permission checks in memory service, RLS', scoring_guidance: { '0': 'No permissions', '1': 'Owner-only check', '2': 'Basic read/write permissions', '3': 'Role-based memory permissions', '4': 'Granular permissions + audit', '5': 'Full permission fabric with delegation' }, risk_if_missing: 'Cross-tenant memory exposure', remediation_guidance: 'Add RLS + service-level permission checks on all memory operations', weight: 1.5, severity: 'critical', is_required: true },
        { id: 'c-02-03', domain_id: 'd-02', name: 'Semantic Memory Search', description: 'Memory searchable via semantic similarity', expected_standard: 'Vector embeddings enable semantic retrieval', evidence_required: 'Embedding pipeline, vector search function, retrieval tests', scoring_guidance: { '0': 'No search', '1': 'Full-text only', '2': 'Keyword + basic filter', '3': 'Vector search working', '4': 'Hybrid vector + full-text', '5': 'Hybrid + re-ranking + freshness scoring' }, risk_if_missing: 'Agents cannot retrieve relevant memory efficiently', remediation_guidance: 'Add pgvector embeddings + semantic search function', weight: 1.5, severity: 'high', is_required: true },
        { id: 'c-02-04', domain_id: 'd-02', name: 'Memory Audit Trail', description: 'All memory operations logged', expected_standard: 'Every memory create/update/delete produces an audit log', evidence_required: 'memory_audit_logs table, trigger or service logging', scoring_guidance: { '0': 'No audit', '1': 'Manual logging', '2': 'Some operations logged', '3': 'All operations logged', '4': 'Logs + before/after states', '5': 'Immutable audit trail with replay support' }, risk_if_missing: 'Cannot investigate memory manipulation or corruption', remediation_guidance: 'Implement memory_audit_logs with before/after state capture', weight: 1.0, severity: 'high', is_required: false },
        { id: 'c-02-05', domain_id: 'd-02', name: 'Memory Expiry & Pruning', description: 'Memory can be expired, pruned, and summarized', expected_standard: 'TTL-based expiry + manual pruning + auto-summarization', evidence_required: 'Expiry logic, pruning jobs, summarizer service', scoring_guidance: { '0': 'No expiry', '1': 'Manual deletion only', '2': 'TTL expiry only', '3': 'TTL + manual prune', '4': 'Auto prune + summarize', '5': 'Intelligent pruning with importance scoring' }, risk_if_missing: 'Memory bloat, privacy violations, degraded retrieval quality', remediation_guidance: 'Implement expires_at + background pruning job + summarizer', weight: 1.0, severity: 'medium', is_required: false },
      ],
    },
    {
      id: 'd-03', name: 'Agent Orchestration Layer', slug: 'agent-orchestration',
      description: 'Agent registry, runner, handoffs, lifecycle, and tracing',
      weight: 0.12,
      controls: [
        { id: 'c-03-01', domain_id: 'd-03', name: 'Agent Registry', description: 'Central registry of all agent definitions', expected_standard: 'All agents registered with typed capabilities and roles', evidence_required: 'agent_definitions table, registry API', scoring_guidance: { '0': 'No registry', '1': 'Hardcoded agents', '2': 'Config file registry', '3': 'Database registry', '4': 'Versioned registry + capabilities', '5': 'Full registry with health checks + capability discovery' }, risk_if_missing: 'Uncontrolled agent proliferation, no governance', remediation_guidance: 'Implement agent_definitions table + registry service', weight: 2.0, severity: 'high', is_required: true },
        { id: 'c-03-02', domain_id: 'd-03', name: 'Agent Runs Logged', description: 'Every agent execution is traced and logged', expected_standard: 'All agent runs create agent_runs + agent_run_steps records', evidence_required: 'Trace tables, run logging in agent runner', scoring_guidance: { '0': 'No logging', '1': 'Console logs only', '2': 'Database logging partial', '3': 'Full run logging', '4': 'Run + steps + token metrics', '5': 'Full trace + cost + replay support' }, risk_if_missing: 'Cannot debug agent failures or audit decisions', remediation_guidance: 'Wrap every agent execution in run + step logging', weight: 2.0, severity: 'critical', is_required: true },
        { id: 'c-03-03', domain_id: 'd-03', name: 'Agent Handoffs Deterministic', description: 'Agent-to-agent handoffs are explicit and logged', expected_standard: 'Handoffs use typed contracts with context transfer', evidence_required: 'agent_handoffs table, handoff protocol code', scoring_guidance: { '0': 'No formal handoffs', '1': 'Ad hoc passing', '2': 'Simple routing only', '3': 'Typed handoff contracts', '4': 'Typed + logged + validated', '5': 'Full handoff protocol with rollback' }, risk_if_missing: 'Lost context between agents, invisible failures', remediation_guidance: 'Implement formal handoff protocol with context transfer validation', weight: 1.5, severity: 'high', is_required: true },
        { id: 'c-03-04', domain_id: 'd-03', name: 'Agent Failure Fallbacks', description: 'Agent failures have defined fallback behavior', expected_standard: 'Every agent has retry logic and fallback agent or error handling', evidence_required: 'Retry configuration, fallback agent config, error tests', scoring_guidance: { '0': 'No fallbacks', '1': 'Generic error only', '2': 'Retry exists', '3': 'Retry + fallback agent', '4': 'Retry + fallback + human escalation', '5': 'Full resilience: retry, fallback, circuit breaker, human' }, risk_if_missing: 'Silent failures, orphaned workflows', remediation_guidance: 'Define retry_count + fallback_agent_id + escalation path per agent', weight: 1.5, severity: 'high', is_required: true },
        { id: 'c-03-05', domain_id: 'd-03', name: 'Token/Cost Governance', description: 'Agent token usage and cost tracked and bounded', expected_standard: 'Each agent has token budget; costs captured per run', evidence_required: 'max_tokens config, cost_usd in agent_runs, cost dashboards', scoring_guidance: { '0': 'No cost tracking', '1': 'Token count only', '2': 'Token + basic cost', '3': 'Per-run cost logging', '4': 'Budget enforcement + alerts', '5': 'Budget + optimization + tenant billing' }, risk_if_missing: 'Runaway AI costs, no optimization signal', remediation_guidance: 'Add max_tokens limits + cost logging + alert thresholds', weight: 1.0, severity: 'medium', is_required: false },
      ],
    },
    {
      id: 'd-04', name: 'Tool / Action Execution Layer', slug: 'tool-execution',
      description: 'Tool registry, schemas, permissions, idempotency, and verification',
      weight: 0.10,
      controls: [
        { id: 'c-04-01', domain_id: 'd-04', name: 'Tool Registry Exists', description: 'All tools registered with typed schemas', expected_standard: 'Central tool registry with Zod-validated input/output schemas', evidence_required: 'tool_definitions table, schema validation code', scoring_guidance: { '0': 'No registry', '1': 'Hardcoded tool list', '2': 'Config-based registry', '3': 'Database registry + schemas', '4': 'Registry + versioned schemas + health checks', '5': 'Full tool bus with capability discovery' }, risk_if_missing: 'Uncontrolled tool execution, no schema validation', remediation_guidance: 'Implement tool_definitions with JSON Schema + Zod validation', weight: 2.0, severity: 'high', is_required: true },
        { id: 'c-04-02', domain_id: 'd-04', name: 'Tool Permission Checks', description: 'All tool calls are permission-checked before execution', expected_standard: 'Every tool invocation validates actor permissions', evidence_required: 'Permission middleware, permission tests, denied invocations log', scoring_guidance: { '0': 'No permission checks', '1': 'Auth check only', '2': 'Role check', '3': 'Tool-specific permissions', '4': 'Granular + logged', '5': 'Full permission fabric with policy integration' }, risk_if_missing: 'Unauthorized tool execution, data manipulation', remediation_guidance: 'Add tool_permissions table + permission check middleware', weight: 2.0, severity: 'critical', is_required: true },
        { id: 'c-04-03', domain_id: 'd-04', name: 'Idempotent Tool Calls', description: 'Tool calls are safe to retry without double-execution', expected_standard: 'Idempotency keys on all state-changing tool calls', evidence_required: 'idempotency_key column, deduplication logic', scoring_guidance: { '0': 'No idempotency', '1': 'Manual per-tool', '2': 'Partial coverage', '3': 'Idempotency keys on all writes', '4': 'Keys + dedup + test coverage', '5': 'Full idempotency mesh with TTL and replay' }, risk_if_missing: 'Duplicate actions on retry — money sent twice, records duplicated', remediation_guidance: 'Add idempotency_key to tool_invocations with ON CONFLICT handling', weight: 1.5, severity: 'critical', is_required: true },
        { id: 'c-04-04', domain_id: 'd-04', name: 'Human Approval Gates', description: 'High-risk tools require human approval before execution', expected_standard: 'requires_approval flag + approval workflow for risk >= high', evidence_required: 'action_approvals table, approval UI, blocked execution on pending', scoring_guidance: { '0': 'No approval gates', '1': 'Manual escalation only', '2': 'Some tools gated', '3': 'Risk-based gating', '4': 'Auto-routing to approvers', '5': 'Full approval workflow with SLA + escalation' }, risk_if_missing: 'Autonomous execution of dangerous actions without oversight', remediation_guidance: 'Implement approval workflow for requires_approval=true tools', weight: 1.5, severity: 'critical', is_required: true },
        { id: 'c-04-05', domain_id: 'd-04', name: 'Tool Result Verification', description: 'Tool outputs are validated before consumption', expected_standard: 'Output schema validation + post-execution verification hooks', evidence_required: 'Output schema validation code, verification test cases', scoring_guidance: { '0': 'No verification', '1': 'Type check only', '2': 'Schema validation', '3': 'Schema + business rule checks', '4': 'Full verification + retry on invalid', '5': 'Verification + QA agent review for critical tools' }, risk_if_missing: 'Corrupt or invalid tool outputs consumed by downstream agents', remediation_guidance: 'Add Zod output schema validation on all tool results', weight: 1.0, severity: 'high', is_required: false },
      ],
    },
    {
      id: 'd-05', name: 'Workflow & Automation Engine', slug: 'workflow-engine',
      description: 'Event-driven workflows, state machines, queues, retry, and dead letters',
      weight: 0.10,
      controls: [
        { id: 'c-05-01', domain_id: 'd-05', name: 'Event-Driven Workflows', description: 'Workflows triggered by events not polling', expected_standard: 'Workflow engine uses event queue for all triggers', evidence_required: 'workflow_queue table, event publisher, trigger code', scoring_guidance: { '0': 'No workflows', '1': 'Manual triggers only', '2': 'Scheduled polling', '3': 'Event-driven queue', '4': 'Event-driven + priority + ordering', '5': 'Full event mesh with replay and fan-out' }, risk_if_missing: 'Brittle automation, missed events, polling overhead', remediation_guidance: 'Implement workflow_queue with event publisher/subscriber pattern', weight: 2.0, severity: 'high', is_required: true },
        { id: 'c-05-02', domain_id: 'd-05', name: 'Stateful Workflow Runs', description: 'Workflow state persisted and resumable', expected_standard: 'Workflow runs persist step-by-step state with pause/resume', evidence_required: 'workflow_runs + workflow_steps tables, state machine', scoring_guidance: { '0': 'Stateless only', '1': 'Basic status tracking', '2': 'Step tracking', '3': 'Full state machine', '4': 'State machine + compensation paths', '5': 'Full durable execution with replay' }, risk_if_missing: 'Workflow restarts from scratch on failure', remediation_guidance: 'Implement workflow_steps with current_step tracking and resume logic', weight: 2.0, severity: 'high', is_required: true },
        { id: 'c-05-03', domain_id: 'd-05', name: 'Dead-Letter Queue', description: 'Failed jobs captured and retrievable', expected_standard: 'Failed workflow events go to dead-letter queue for inspection', evidence_required: 'workflow_dead_letters table, DLQ processor', scoring_guidance: { '0': 'No DLQ', '1': 'Logs only', '2': 'Manual capture', '3': 'Auto-capture to DLQ', '4': 'DLQ + alert + retry UI', '5': 'DLQ + root cause analysis + auto-remediation' }, risk_if_missing: 'Failed events are silently lost', remediation_guidance: 'Implement workflow_dead_letters with automatic routing on max_retries exceeded', weight: 1.5, severity: 'high', is_required: true },
        { id: 'c-05-04', domain_id: 'd-05', name: 'Workflow Retry Logic', description: 'Failed workflow steps are retried with backoff', expected_standard: 'Exponential backoff retry with configurable max_retries', evidence_required: 'Retry logic code, retry_count in tables, backoff calculation', scoring_guidance: { '0': 'No retry', '1': 'Manual retry only', '2': 'Fixed retry', '3': 'Exponential backoff', '4': 'Backoff + jitter + alerts', '5': 'Full retry mesh with circuit breaker' }, risk_if_missing: 'Transient failures cause permanent workflow failure', remediation_guidance: 'Implement retry with exponential backoff: delay = 2^retry_count * base_ms', weight: 1.5, severity: 'high', is_required: true },
        { id: 'c-05-05', domain_id: 'd-05', name: 'Workflow Pause/Resume', description: 'Workflows can be paused for approval and resumed', expected_standard: 'Approval steps pause workflow until explicit approval received', evidence_required: 'Pause state, resume logic, approval step integration', scoring_guidance: { '0': 'No pause/resume', '1': 'Manual stop only', '2': 'Pause only, no resume', '3': 'Pause + resume', '4': 'Pause + approval gate + timeout', '5': 'Full pause/resume with human-in-the-loop workflow' }, risk_if_missing: 'Cannot implement human oversight in automated workflows', remediation_guidance: 'Add awaiting_approval status to workflow_runs + approval integration', weight: 1.0, severity: 'medium', is_required: false },
      ],
    },
    {
      id: 'd-06', name: 'Knowledge / Retrieval Layer', slug: 'knowledge-layer',
      description: 'Source registry, chunking, embeddings, retrieval, freshness, and provenance',
      weight: 0.08,
      controls: [
        { id: 'c-06-01', domain_id: 'd-06', name: 'Knowledge Source Registry', description: 'All knowledge sources registered and tracked', expected_standard: 'knowledge_sources table with trust score and freshness', evidence_required: 'knowledge_sources table, source management UI', scoring_guidance: { '0': 'No registry', '1': 'Hardcoded sources', '2': 'Config-based', '3': 'Database registry', '4': 'Registry + trust scores + freshness', '5': 'Full source mesh with provenance chain' }, risk_if_missing: 'Unknown sources used in retrieval — hallucination risk', remediation_guidance: 'Implement knowledge_sources with trust_score and freshness tracking', weight: 1.5, severity: 'high', is_required: true },
        { id: 'c-06-02', domain_id: 'd-06', name: 'Tenant-Aware Retrieval', description: 'Knowledge retrieval scoped to tenant', expected_standard: 'All retrieval queries filter by organization_id', evidence_required: 'RLS policies on knowledge tables, retrieval service code', scoring_guidance: { '0': 'No tenant scope', '1': 'Manual filtering', '2': 'Some scoping', '3': 'Consistent tenant scoping', '4': 'Tenant scoped + permission aware', '5': 'Full tenant mesh with cross-tenant sharing controls' }, risk_if_missing: 'Knowledge leakage across tenants', remediation_guidance: 'Add organization_id filter + RLS on knowledge_chunks', weight: 2.0, severity: 'critical', is_required: true },
        { id: 'c-06-03', domain_id: 'd-06', name: 'Hybrid Retrieval', description: 'Retrieval combines semantic and keyword search', expected_standard: 'pgvector + full-text search combined with ranking', evidence_required: 'Hybrid retrieval function, retrieval quality tests', scoring_guidance: { '0': 'No retrieval', '1': 'Keyword only', '2': 'Vector only', '3': 'Hybrid retrieval', '4': 'Hybrid + re-ranking', '5': 'Hybrid + re-ranking + freshness + trust scoring' }, risk_if_missing: 'Poor retrieval quality, hallucinations from missing context', remediation_guidance: 'Implement hybrid retrieval combining vector similarity + tsvector search', weight: 1.5, severity: 'high', is_required: true },
        { id: 'c-06-04', domain_id: 'd-06', name: 'Freshness Tracking', description: 'Knowledge chunk freshness tracked and decayed', expected_standard: 'Freshness score decays over time, stale chunks deprioritized', evidence_required: 'freshness_score column, decay function, freshness in retrieval ranking', scoring_guidance: { '0': 'No freshness', '1': 'Created_at only', '2': 'Manual expiry', '3': 'Freshness score', '4': 'Auto-decay + re-ranking', '5': 'Predictive freshness with source monitoring' }, risk_if_missing: 'Outdated knowledge used for decisions', remediation_guidance: 'Add freshness_score with time-decay function applied during retrieval', weight: 1.0, severity: 'medium', is_required: false },
        { id: 'c-06-05', domain_id: 'd-06', name: 'Hallucination Controls', description: 'Retrieval output validated against source', expected_standard: 'Citation tracking and factual grounding checks on RAG output', evidence_required: 'Citation metadata in responses, grounding validation code', scoring_guidance: { '0': 'No controls', '1': 'Manual review', '2': 'Basic citation tracking', '3': 'Citations + confidence scores', '4': 'Citations + automated factual check', '5': 'Full hallucination detection + QA agent review' }, risk_if_missing: 'AI confidently states incorrect facts', remediation_guidance: 'Require citations in all RAG responses + implement confidence threshold checks', weight: 1.5, severity: 'high', is_required: true },
      ],
    },
    {
      id: 'd-07', name: 'Decisioning & Policy Engine', slug: 'policy-engine',
      description: 'Policy definitions, rules engine, risk scoring, and explainable decisions',
      weight: 0.10,
      controls: [
        { id: 'c-07-01', domain_id: 'd-07', name: 'Explicit Policy Rules', description: 'All access and action policies defined explicitly', expected_standard: 'policy_definitions with typed rules covering all critical paths', evidence_required: 'policy_definitions table, rules engine code', scoring_guidance: { '0': 'No policies', '1': 'Hardcoded logic', '2': 'Config-based rules', '3': 'Database policy definitions', '4': 'Versioned policies + hierarchy', '5': 'Full policy fabric with simulation' }, risk_if_missing: 'Inconsistent access control, unauditable decisions', remediation_guidance: 'Implement policy_definitions with rules engine + hierarchy: system > org > workspace', weight: 2.0, severity: 'critical', is_required: true },
        { id: 'c-07-02', domain_id: 'd-07', name: 'Policy Evaluations Logged', description: 'Every policy evaluation produces a decision record', expected_standard: 'All policy checks create decision_records', evidence_required: 'decision_records table, logging in policy evaluator', scoring_guidance: { '0': 'No logging', '1': 'Audit log only', '2': 'Some decisions logged', '3': 'All decisions logged', '4': 'Decisions + reasoning + override tracking', '5': 'Full decision audit chain with replay' }, risk_if_missing: 'Cannot audit why access was granted or denied', remediation_guidance: 'Log all policy evaluations to decision_records with reasoning', weight: 1.5, severity: 'high', is_required: true },
        { id: 'c-07-03', domain_id: 'd-07', name: 'Risk Scoring', description: 'Risk score computed for all significant actions', expected_standard: 'Risk score (0-1) computed before high-risk operations', evidence_required: 'Risk scoring function, risk_score in decision_records', scoring_guidance: { '0': 'No risk scoring', '1': 'Manual risk flags only', '2': 'Static risk levels', '3': 'Dynamic risk scoring', '4': 'ML-based risk + explainability', '5': 'Contextual risk engine with learning' }, risk_if_missing: 'High-risk actions executed without assessment', remediation_guidance: 'Build risk scoring function with configurable rules per action type', weight: 1.5, severity: 'high', is_required: true },
        { id: 'c-07-04', domain_id: 'd-07', name: 'Human Override', description: 'Policy decisions can be overridden with documented reason', expected_standard: 'Authorized users can override policy decisions with audit trail', evidence_required: 'Override UI, overridden_by + override_reason in decision_records', scoring_guidance: { '0': 'No override', '1': 'Manual workaround', '2': 'Override exists no logging', '3': 'Override + logging', '4': 'Override + logging + notification', '5': 'Full override workflow with approval chain' }, risk_if_missing: 'Policy system becomes a blocker with no legitimate escape valve', remediation_guidance: 'Implement override endpoint with mandatory reason + audit trail', weight: 1.0, severity: 'medium', is_required: false },
        { id: 'c-07-05', domain_id: 'd-07', name: 'Explainable Decisions', description: 'Policy decisions include human-readable explanations', expected_standard: 'Every decision record includes reasoning text', evidence_required: 'reasoning field in decision_records, explanation UI', scoring_guidance: { '0': 'No explanation', '1': 'Code error only', '2': 'Generic message', '3': 'Rule-specific explanation', '4': 'Natural language explanation', '5': 'Full decision tree visualization + what-if simulation' }, risk_if_missing: 'Users denied access with no explanation — poor UX and compliance risk', remediation_guidance: 'Generate natural language reasoning for all policy decisions', weight: 1.0, severity: 'medium', is_required: false },
      ],
    },
    {
      id: 'd-08', name: 'Interface & Experience Layer', slug: 'interface-layer',
      description: 'AI action transparency, approval UIs, audit dashboards, progress visibility',
      weight: 0.06,
      controls: [
        { id: 'c-08-01', domain_id: 'd-08', name: 'AI Action Transparency', description: 'Users can see what AI is doing and why', expected_standard: 'AI actions displayed with reasoning and confidence in UI', evidence_required: 'Action transparency UI components, confidence indicators', scoring_guidance: { '0': 'No visibility', '1': 'Status message only', '2': 'Basic action log', '3': 'Action log + reasoning', '4': 'Real-time transparency + confidence', '5': 'Full AI OS dashboard with drill-down' }, risk_if_missing: 'Users distrust AI system they cannot observe', remediation_guidance: 'Build agent execution timeline UI with reasoning and confidence', weight: 1.5, severity: 'high', is_required: true },
        { id: 'c-08-02', domain_id: 'd-08', name: 'Approval Interfaces', description: 'Users can approve/reject risky AI actions', expected_standard: 'Approval modals with context, impact, and decision controls', evidence_required: 'Approval modal UI, approval API route, tested user flow', scoring_guidance: { '0': 'No approval UI', '1': 'Manual process', '2': 'Basic confirmation', '3': 'Approval modal with context', '4': 'Full approval workflow UI', '5': 'Approval UI + SLA countdown + delegation' }, risk_if_missing: 'Human-in-the-loop breaks down — dangerous actions proceed unreviewed', remediation_guidance: 'Build approval modal with action context, risk score, and decision buttons', weight: 1.5, severity: 'critical', is_required: true },
        { id: 'c-08-03', domain_id: 'd-08', name: 'Audit Result UI', description: 'Audit scores and results clearly displayed', expected_standard: 'Audit center with scorecard, gap register, lapse register, and roadmap', evidence_required: 'Audit dashboard screens, certification display', scoring_guidance: { '0': 'No audit UI', '1': 'Raw JSON only', '2': 'Basic table', '3': 'Scorecard UI', '4': 'Scorecard + gap/lapse registers', '5': 'Full audit center with certification and export' }, risk_if_missing: 'Audit results inaccessible to non-technical stakeholders', remediation_guidance: 'Build audit center with visual scorecards and remediation roadmap', weight: 1.0, severity: 'medium', is_required: true },
        { id: 'c-08-04', domain_id: 'd-08', name: 'Error Visibility', description: 'System errors visible and actionable in UI', expected_standard: 'All errors displayed with user-friendly messages and actions', evidence_required: 'Error boundary components, error state designs', scoring_guidance: { '0': 'No error UI', '1': 'Raw error messages', '2': 'Generic error page', '3': 'Typed error messages', '4': 'Contextual errors + retry actions', '5': 'Proactive error prevention + smart recovery' }, risk_if_missing: 'Users confused by silent failures or cryptic errors', remediation_guidance: 'Implement error boundaries with user-friendly messages + recovery actions', weight: 1.0, severity: 'medium', is_required: false },
        { id: 'c-08-05', domain_id: 'd-08', name: 'Progress Visibility', description: 'Long-running operations show progress', expected_standard: 'Workflow and agent runs show real-time progress', evidence_required: 'Progress indicators, websocket or polling updates', scoring_guidance: { '0': 'No progress UI', '1': 'Spinner only', '2': 'Step count', '3': 'Step names + progress', '4': 'Real-time updates', '5': 'Live timeline with step details + ETA' }, risk_if_missing: 'Users abandon or re-trigger long operations thinking they stalled', remediation_guidance: 'Add progress polling to workflow/agent run pages with step-by-step display', weight: 1.0, severity: 'low', is_required: false },
      ],
    },
    {
      id: 'd-09', name: 'Security, Trust & Governance', slug: 'security-governance',
      description: 'RLS, RBAC, prompt injection, audit logs, secrets, and compliance controls',
      weight: 0.14,
      controls: [
        { id: 'c-09-01', domain_id: 'd-09', name: 'RLS Enforced', description: 'Row-level security on all tenant-scoped tables', expected_standard: 'All tables with org data have RLS policies', evidence_required: 'pg_policies view showing RLS on all tables', scoring_guidance: { '0': 'No RLS', '1': 'Some tables', '2': 'Most tables', '3': 'All tables covered', '4': 'All tables + tested with multi-tenant fixtures', '5': 'Full RLS coverage + penetration tested' }, risk_if_missing: 'Cross-tenant data breach — catastrophic', remediation_guidance: 'Enable RLS on every tenant-scoped table with tenant_isolation policy', weight: 3.0, severity: 'critical', is_required: true },
        { id: 'c-09-02', domain_id: 'd-09', name: 'Least Privilege Enforced', description: 'All operations use minimum required permissions', expected_standard: 'Service accounts and API keys have minimal scopes', evidence_required: 'Permission scopes in api_keys, service_accounts allowed_actions', scoring_guidance: { '0': 'Admin everywhere', '1': 'Role-based only', '2': 'Scoped roles', '3': 'Granular permissions', '4': 'Audited permissions + review process', '5': 'Zero-trust + just-in-time access' }, risk_if_missing: 'Breached service account has full system access', remediation_guidance: 'Define minimal permission scopes per service and API key', weight: 2.0, severity: 'critical', is_required: true },
        { id: 'c-09-03', domain_id: 'd-09', name: 'Prompt Injection Detection', description: 'AI inputs scanned for injection attempts', expected_standard: 'Prompt injection scanner on all user inputs to AI', evidence_required: 'prompt_injection_events table, scanner implementation', scoring_guidance: { '0': 'No detection', '1': 'Manual review', '2': 'Basic pattern matching', '3': 'Pattern + semantic detection', '4': 'ML-based detection + blocking', '5': 'Real-time detection + sandboxing + audit' }, risk_if_missing: 'Attacker bypasses AI guardrails via crafted inputs', remediation_guidance: 'Implement prompt injection scanner as middleware before AI invocations', weight: 2.0, severity: 'critical', is_required: true },
        { id: 'c-09-04', domain_id: 'd-09', name: 'Immutable Audit Logs', description: 'All sensitive actions produce immutable audit logs', expected_standard: 'audit_logs table with no UPDATE/DELETE permissions + append-only', evidence_required: 'No update/delete RLS policy on audit_logs, log integrity test', scoring_guidance: { '0': 'No audit logs', '1': 'Mutable logs', '2': 'Logs exist but deletable', '3': 'Append-only logs', '4': 'Append-only + integrity hashing', '5': 'Tamper-evident + external archival' }, risk_if_missing: 'Cannot prove system behaviour — compliance failure', remediation_guidance: 'Implement audit_logs as append-only: SELECT + INSERT only, no UPDATE/DELETE', weight: 2.0, severity: 'critical', is_required: true },
        { id: 'c-09-05', domain_id: 'd-09', name: 'Secrets Isolation', description: 'All secrets stored in environment, never in code', expected_standard: 'Zero secrets in codebase; all via environment variables or vault', evidence_required: 'No API keys in code, .env.example, secrets management docs', scoring_guidance: { '0': 'Secrets in code', '1': 'Some in env', '2': 'All in env, no rotation', '3': 'Env + documented rotation', '4': 'Env + rotation + audit', '5': 'Vault integration + automated rotation + breach detection' }, risk_if_missing: 'Secret exposure via code repository', remediation_guidance: 'Audit codebase for secrets, move all to env vars, implement git-secrets', weight: 1.5, severity: 'critical', is_required: true },
      ],
    },
    {
      id: 'd-10', name: 'Observability, Telemetry & Reliability', slug: 'observability',
      description: 'Traces, metrics, costs, failure classification, replay, and reliability SLOs',
      weight: 0.08,
      controls: [
        { id: 'c-10-01', domain_id: 'd-10', name: 'Distributed Tracing', description: 'All agent/tool/workflow actions are traced end-to-end', expected_standard: 'telemetry_traces with trace_id, span hierarchy, and duration', evidence_required: 'telemetry_traces table, trace creation in agent/tool/workflow runners', scoring_guidance: { '0': 'No tracing', '1': 'Log-based only', '2': 'Basic request tracing', '3': 'Full distributed tracing', '4': 'Tracing + cost + quality metrics', '5': 'Full observability: trace + metric + log + replay' }, risk_if_missing: 'Cannot diagnose system behaviour in production', remediation_guidance: 'Implement distributed tracing with trace_id propagation across all operations', weight: 2.0, severity: 'high', is_required: true },
        { id: 'c-10-02', domain_id: 'd-10', name: 'Cost Metrics Captured', description: 'AI token usage and cost tracked per tenant', expected_standard: 'cost_metrics aggregated daily per model and workspace', evidence_required: 'cost_metrics table, cost tracking in agent runner', scoring_guidance: { '0': 'No cost tracking', '1': 'Rough estimate only', '2': 'Per-run cost', '3': 'Per-tenant daily cost', '4': 'Tenant + workspace + model breakdown', '5': 'Real-time cost dashboard + budget alerts + billing' }, risk_if_missing: 'Runaway AI costs undetected', remediation_guidance: 'Capture tokens_in/tokens_out + cost_usd on every AI call, aggregate daily', weight: 1.5, severity: 'high', is_required: true },
        { id: 'c-10-03', domain_id: 'd-10', name: 'Failure Classification', description: 'Failures classified by type for analysis', expected_standard: 'error_code + error_message in all failure records', evidence_required: 'Error code taxonomy, failure classification in traces and runs', scoring_guidance: { '0': 'No classification', '1': 'Binary pass/fail', '2': 'Error messages only', '3': 'Error code taxonomy', '4': 'Taxonomy + root cause tagging', '5': 'Automated failure analysis + prediction' }, risk_if_missing: 'Cannot identify systemic failure patterns', remediation_guidance: 'Implement error code taxonomy and classify all failures at capture time', weight: 1.5, severity: 'medium', is_required: true },
        { id: 'c-10-04', domain_id: 'd-10', name: 'Replay Capability', description: 'Failed runs can be replayed for debugging', expected_standard: 'Any run can be replayed with same inputs and context snapshot', evidence_required: 'Replay endpoint, replay tests, context snapshot integration', scoring_guidance: { '0': 'No replay', '1': 'Manual re-trigger', '2': 'Input capture only', '3': 'Input + context replay', '4': 'Full run replay with comparison', '5': 'Deterministic replay with diff reporting' }, risk_if_missing: 'Cannot reproduce and fix intermittent failures', remediation_guidance: 'Capture full run input + context snapshot to enable deterministic replay', weight: 1.0, severity: 'medium', is_required: false },
        { id: 'c-10-05', domain_id: 'd-10', name: 'Reliability Alerts', description: 'Automated alerts on reliability degradation', expected_standard: 'SLO-based alerts when failure rate or latency exceeds threshold', evidence_required: 'Alert configuration, alert history, SLO definitions', scoring_guidance: { '0': 'No alerts', '1': 'Manual monitoring', '2': 'Basic uptime alerts', '3': 'SLO-based alerts', '4': 'SLO alerts + escalation', '5': 'Predictive alerts + auto-remediation' }, risk_if_missing: 'Reliability degradation goes undetected until user complaints', remediation_guidance: 'Define error rate and latency SLOs, set up alert rules with escalation', weight: 1.0, severity: 'high', is_required: false },
      ],
    },
    {
      id: 'd-11', name: 'Interoperability & Extensibility', slug: 'extensibility',
      description: 'Plugin architecture, provider abstraction, SDK, and extension points',
      weight: 0.08,
      controls: [
        { id: 'c-11-01', domain_id: 'd-11', name: 'Plugin System Exists', description: 'External plugins can extend the system', expected_standard: 'Plugin manifest spec + installation + permission model', evidence_required: 'plugin_definitions table, plugin loader, example plugin', scoring_guidance: { '0': 'No plugins', '1': 'Hardcoded integrations only', '2': 'Config-based extensions', '3': 'Plugin manifest system', '4': 'Plugin system + marketplace', '5': 'Full plugin ecosystem with sandboxing + monetization' }, risk_if_missing: 'Platform locked to built-in tools only — not extensible', remediation_guidance: 'Implement plugin manifest spec + loader + example plugin', weight: 2.0, severity: 'medium', is_required: true },
        { id: 'c-11-02', domain_id: 'd-11', name: 'Provider Abstraction', description: 'AI providers are swappable without code changes', expected_standard: 'Provider abstraction layer supporting multiple AI providers', evidence_required: 'AIProvider interface, adapters for Anthropic + OpenAI, config-based switching', scoring_guidance: { '0': 'Single hardcoded provider', '1': 'Provider flag exists', '2': 'Two providers with duplication', '3': 'Clean abstraction layer', '4': 'Full adapter pattern + tested', '5': 'Provider mesh with fallback routing' }, risk_if_missing: 'Vendor lock-in to single AI provider', remediation_guidance: 'Implement AIProvider abstract interface with adapters per provider', weight: 1.5, severity: 'high', is_required: true },
        { id: 'c-11-03', domain_id: 'd-11', name: 'SDK Available', description: 'Developer SDK for building on the platform', expected_standard: 'Published SDK with typed client, auth, and core service access', evidence_required: 'SDK package, SDK docs, example usage', scoring_guidance: { '0': 'No SDK', '1': 'API docs only', '2': 'Minimal client library', '3': 'Typed SDK', '4': 'SDK + examples + versioning', '5': 'Full SDK + CLI + scaffolding tools' }, risk_if_missing: 'Hard for developers to build on the platform', remediation_guidance: 'Publish @zenith-aios/sdk with typed client and authentication helpers', weight: 1.5, severity: 'medium', is_required: false },
        { id: 'c-11-04', domain_id: 'd-11', name: 'API Contracts Versioned', description: 'APIs have explicit version strategy', expected_standard: 'API versioning in URL or header with backward compatibility policy', evidence_required: 'API version in routes, changelog, deprecation notices', scoring_guidance: { '0': 'No versioning', '1': 'Date-based implicit', '2': 'Version in URL', '3': 'Versioned + changelog', '4': 'Versioned + compatibility matrix', '5': 'Full API governance with spec-first design' }, risk_if_missing: 'Breaking API changes break integrations without warning', remediation_guidance: 'Add /v1/ prefix to API routes, maintain changelog, declare deprecation policy', weight: 1.0, severity: 'medium', is_required: false },
        { id: 'c-11-05', domain_id: 'd-11', name: 'Extension Points Documented', description: 'Documented extension points for each module', expected_standard: 'Developer guide explains how to extend each AI OS module', evidence_required: 'Extension point docs, interface definitions per module', scoring_guidance: { '0': 'No documentation', '1': 'README only', '2': 'Module docs', '3': 'Extension guide', '4': 'Extension guide + examples', '5': 'Interactive developer portal' }, risk_if_missing: 'Extension requires reading source code — high barrier', remediation_guidance: 'Document extension interfaces for all 13 AI OS modules', weight: 1.0, severity: 'low', is_required: false },
      ],
    },
    {
      id: 'd-12', name: 'Deployment, Portability & Open-Standard Readiness', slug: 'deployment-portability',
      description: 'Docker, self-host, docs, standard manifests, contribution guide, and certification harness',
      weight: 0.06,
      controls: [
        { id: 'c-12-01', domain_id: 'd-12', name: 'Local Dev Works', description: 'Developer can run the system locally with single command', expected_standard: 'Docker compose up or equivalent boots full stack locally', evidence_required: 'docker-compose.yml, local dev docs, tested setup', scoring_guidance: { '0': 'No local dev', '1': 'Partial manual setup', '2': 'Manual multi-step', '3': 'Docker compose', '4': 'One-command setup + seed data', '5': 'Dev container + codespace support' }, risk_if_missing: 'High contributor friction — platform hard to develop on', remediation_guidance: 'Create docker-compose.yml + start script + seed data for local dev', weight: 1.5, severity: 'medium', is_required: true },
        { id: 'c-12-02', domain_id: 'd-12', name: 'Deployment Docs', description: 'Clear deployment documentation for all targets', expected_standard: 'Deployment guides for Vercel, Supabase, and self-hosted', evidence_required: 'docs/deployment/ with guides per target', scoring_guidance: { '0': 'No docs', '1': 'README notes only', '2': 'One target documented', '3': 'Two targets documented', '4': 'All targets + troubleshooting', '5': 'Deployment guides + runbook + SLA targets' }, risk_if_missing: 'Platform fails to deploy outside development environment', remediation_guidance: 'Write deployment guides for Vercel, Supabase, and Docker self-host', weight: 1.5, severity: 'medium', is_required: true },
        { id: 'c-12-03', domain_id: 'd-12', name: 'Self-Host Option', description: 'Platform can be self-hosted without vendor dependencies', expected_standard: 'Self-host documented and tested with all features functional', evidence_required: 'Self-host guide, Docker images, self-host test results', scoring_guidance: { '0': 'Cloud-only', '1': 'Theoretical self-host', '2': 'Basic self-host with limitations', '3': 'Full self-host documented', '4': 'Self-host + automated tests', '5': 'Self-host + multi-region + HA guide' }, risk_if_missing: 'Enterprise customers cannot meet data sovereignty requirements', remediation_guidance: 'Create self-host Docker image set with environment configuration guide', weight: 1.0, severity: 'high', is_required: false },
        { id: 'c-12-04', domain_id: 'd-12', name: 'Standard Manifests', description: 'AI OS standard manifests define capabilities and interfaces', expected_standard: 'Machine-readable manifests for all AI OS modules', evidence_required: 'docs/standards/ with module manifest files', scoring_guidance: { '0': 'No manifests', '1': 'README descriptions only', '2': 'Informal capability lists', '3': 'Structured manifest files', '4': 'Versioned manifests + schema', '5': 'Open standard submission ready' }, risk_if_missing: 'Platform cannot participate in AI OS standard ecosystem', remediation_guidance: 'Create structured JSON/YAML manifests for all 13 AI OS modules', weight: 1.5, severity: 'medium', is_required: false },
        { id: 'c-12-05', domain_id: 'd-12', name: 'Certification Harness', description: 'Automated tests validate AI OS compliance', expected_standard: 'Test suite validates every audit control programmatically', evidence_required: 'tests/audit/ directory with compliance test suite', scoring_guidance: { '0': 'No test harness', '1': 'Manual checklist only', '2': 'Partial test coverage', '3': 'Automated test suite', '4': 'Full automation + CI integration', '5': 'Continuous compliance monitoring' }, risk_if_missing: 'Compliance claims cannot be verified automatically', remediation_guidance: 'Build tests/audit/ with one test per audit control, integrate with CI', weight: 1.5, severity: 'high', is_required: true },
      ],
    },
  ],
};
